//
// Copyright: (C) 2019 Nestybox Inc.  All rights reserved.
//

package nsenter

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"syscall"

	_ "github.com/nestybox/sysbox-runc/libcontainer/nsenter"
	"github.com/nestybox/sysbox-runc/libcontainer/utils"
	"github.com/sirupsen/logrus"
	"github.com/vishvananda/netlink/nl"
	"golang.org/x/sys/unix"

	"github.com/nestybox/sysbox-fs/domain"
	"github.com/nestybox/sysbox-fs/fuse"
	"github.com/nestybox/sysbox-runc/libcontainer"
)

func init() {
	if len(os.Args) > 1 && os.Args[1] == "nsenter" {
		runtime.GOMAXPROCS(1)
		runtime.LockOSThread()
	}
}

// Pid struct. Utilized by sysbox-runc's nsexec code.
type pid struct {
	Pid           int `json:"pid"`
	PidFirstChild int `json:"pid_first"`
}

//
// NSenterEvent struct serves as a transport abstraction (envelope) to carry
// all the potential messages that can be exchanged between sysbox-fs master
// instance and secondary (forked) ones. These sysbox-fs' auxiliary instances
// are utilized to perform actions over namespaced resources, and as such,
// cannot be executed by sysbox-fs' main instance.
//
// Every bidirectional transaction is represented by an event structure
// (nsenterEvent), which holds both 'request' and 'response' messages, as well
// as the context necessary to complete any action demanding inter-namespace
// message exchanges.
//
type NSenterEvent struct {

	// initPid associated to the targeted container.
	Pid uint32 `json:"pid"`

	// namespace-types to attach to.
	Namespace []domain.NStype `json:"namespace"`

	// Request message to be sent.
	ReqMsg *domain.NSenterMessage `json:"request"`

	// Request message to be received.
	ResMsg *domain.NSenterMessage `json:"response"`
}

//
// Generic getter / setter methods.
//

func (e *NSenterEvent) SetRequestMsg(m *domain.NSenterMessage) {
	e.ReqMsg = m
}

func (e *NSenterEvent) GetRequestMsg() *domain.NSenterMessage {
	return e.ReqMsg
}

func (e *NSenterEvent) SetResponseMsg(m *domain.NSenterMessage) {
	e.ResMsg = m
}

func (e *NSenterEvent) GetResponseMsg() *domain.NSenterMessage {
	return e.ResMsg
}

///////////////////////////////////////////////////////////////////////////////
//
// nsenterEvent methods below execute within the context of sysbox-fs' main
// instance, upon invocation of sysbox-fs' handler logic.
//
///////////////////////////////////////////////////////////////////////////////

//
// Called by sysbox-fs handler routines to parse the response generated
// by sysbox-fs' grand-child processes.
//
func (e *NSenterEvent) processResponse(pipe io.Reader) error {

	// Rawmessage payload to aid in decoding generic messages (see below
	// explanation).
	var payload json.RawMessage
	nsenterMsg := domain.NSenterMessage{
		Payload: &payload,
	}

	// Decode received msg header to help us determine the payload type.
	// Received message will be decoded in two phases. The decode instruction
	// below help us determine the message-type being received. Based on the
	// obtained type, we are able to decode the payload generated by the
	// remote-end. This second step is executed as part of a subsequent
	// unmarshal instruction (see further below).
	if err := json.NewDecoder(pipe).Decode(&nsenterMsg); err != nil {
		logrus.Errorf("Error decoding received nsenterMsg response (%v).", err)
		return errors.New("Error decoding received event response")
	}

	switch nsenterMsg.Type {

	case domain.LookupResponse:
		logrus.Debug("Received nsenterEvent lookupResponse message.")

		var p domain.FileInfo
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		break

	case domain.OpenFileResponse:
		logrus.Debug("Received nsenterEvent OpenResponse message.")

		var p int
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		break

	case domain.ReadFileResponse:
		logrus.Debug("Received nsenterEvent readResponse message.")

		var p string
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		break

	case domain.WriteFileResponse:
		logrus.Debug("Received nsenterEvent writeResponse message.")

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: "",
		}
		break

	case domain.ReadDirResponse:
		logrus.Debug("Received nsenterEvent readDirAllResponse message.")

		var p []domain.FileInfo
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		break

	case domain.MountSyscallResponse:
		logrus.Debug("Received nsenterEvent mountSyscallResponse message.")

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: "",
		}
		break

	case domain.UmountSyscallResponse:
		logrus.Debug("Received nsenterEvent umountSyscallResponse message.")

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: "",
		}
		break

	case domain.ErrorResponse:
		logrus.Debug("Received nsenterEvent errorResponse message.")

		var p syscall.Errno

		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ResMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		break

	default:
		return errors.New("Received unsupported nsenterEvent message.")
	}

	return nil
}

//
// Auxiliary function to obtain the FS path associated to any given namespace.
// Theese FS paths are utilized by sysbox-runc's nsexec logic to enter the
// desired namespaces.
//
// Expected format example: "mnt:/proc/<pid>/ns/mnt"
//
func (e *NSenterEvent) namespacePaths() []string {

	var paths []string

	for _, nstype := range e.Namespace {
		path := filepath.Join(
			nstype,
			":/proc/",
			strconv.Itoa(int(e.Pid)), "/ns/",
			nstype)
		paths = append(paths, path)
	}

	return paths
}

//
// Sysbox-fs requests are generated through this method. Handlers seeking to
// access namespaced resources will call this method to invoke sysbox-runc's
// nsexec logic, which will serve to enter the container namespaces that host
// these resources.
//
func (e *NSenterEvent) SendRequest() error {

	logrus.Debug("Executing nsenterEvent's request() method")

	// Create a socket pair.
	parentPipe, childPipe, err := utils.NewSockPair("nsenterPipe")
	if err != nil {
		return errors.New("Error creating sysbox-fs nsenter pipe")
	}
	defer parentPipe.Close()

	// Obtain the FS path for all the namespaces to be nsenter'ed into, and
	// define the associated netlink-payload to transfer to child process.
	namespaces := e.namespacePaths()

	r := nl.NewNetlinkRequest(int(libcontainer.InitMsg), 0)
	r.AddData(&libcontainer.Bytemsg{
		Type:  libcontainer.NsPathsAttr,
		Value: []byte(strings.Join(namespaces, ",")),
	})

	// Prepare exec.cmd in charged of running: "sysbox-fs nsenter".
	cmd := &exec.Cmd{
		Path:       "/proc/self/exe",
		Args:       []string{os.Args[0], "nsenter"},
		ExtraFiles: []*os.File{childPipe},
		Env:        []string{"_LIBCONTAINER_INITPIPE=3", fmt.Sprintf("GOMAXPROCS=%s", os.Getenv("GOMAXPROCS"))},
		Stdin:      nil,
		Stdout:     nil,
		Stderr:     nil,
	}

	// Launch sysbox-fs' first child process.
	err = cmd.Start()
	childPipe.Close()
	if err != nil {
		return errors.New("Error launching sysbox-fs first child process")
	}

	// Send the config to child process.
	if _, err := io.Copy(parentPipe, bytes.NewReader(r.Serialize())); err != nil {
		return errors.New("Error copying payload to pipe")
	}

	// Wait for sysbox-fs' first child process to finish.
	status, err := cmd.Process.Wait()
	if err != nil {
		cmd.Wait()
		return err
	}
	if !status.Success() {
		cmd.Wait()
		return errors.New("Error waiting for sysbox-fs first child process")
	}

	// Receive sysbox-fs' first-child pid.
	var pid pid
	decoder := json.NewDecoder(parentPipe)
	if err := decoder.Decode(&pid); err != nil {
		cmd.Wait()
		return errors.New("Error receiving first-child pid")
	}

	firstChildProcess, err := os.FindProcess(pid.PidFirstChild)
	if err != nil {
		return err
	}

	// Wait for sysbox-fs' second child process to finish. Ignore the error in
	// case the child has already been reaped for any reason.
	_, _ = firstChildProcess.Wait()

	// Sysbox-fs' third child (grand-child) process remains and will enter the
	// go runtime.
	process, err := os.FindProcess(pid.Pid)
	if err != nil {
		return err
	}
	cmd.Process = process

	// Transfer the nsenterEvent details to grand-child for processing.
	data, err := json.Marshal(*(e.ReqMsg))
	//data, err := json.Marshal(e)
	if err != nil {
		logrus.Errorf("Error while encoding nsenter payload (%v).", err)
		return err
	}
	_, err = parentPipe.Write(data)
	if err != nil {
		logrus.Errorf("Error while writing nsenter payload into pipeline (%v)", err)
		return err
	}

	// Wait for sysbox-fs' grand-child response and process it accordingly.
	ierr := e.processResponse(parentPipe)

	// Destroy the socket pair.
	if err := unix.Shutdown(int(parentPipe.Fd()), unix.SHUT_WR); err != nil {
		return errors.New("Shutting down sysbox-fs nsenter pipe")
	}

	if ierr != nil {
		cmd.Wait()
		return ierr
	}

	// Wait for grand-child exit()
	cmd.Wait()

	return nil
}

func (e *NSenterEvent) ReceiveResponse() *domain.NSenterMessage {

	return e.ResMsg
}

///////////////////////////////////////////////////////////////////////////////
//
// nsenterEvent methods below execute within the context of container
// namespaces. In other words, they are invoked as part of "sysbox-fs nsenter"
// execution.
//
///////////////////////////////////////////////////////////////////////////////

func (e *NSenterEvent) processLookupRequest() error {

	path := e.ReqMsg.Payload.(string)

	// Verify if the resource being looked up is reachable and obtain FileInfo
	// details.
	info, err := os.Stat(path)
	if err != nil {
		// Send an error-message response.
		e.ResMsg = &domain.NSenterMessage{
			Type:    domain.ErrorResponse,
			Payload: &fuse.IOerror{RcvError: err},
		}

		return nil
	}

	// Allocate new FileInfo struct to return to sysbpx-fs' main instance.
	fileInfo := domain.FileInfo{
		Fname:    info.Name(),
		Fsize:    info.Size(),
		Fmode:    info.Mode(),
		FmodTime: info.ModTime(),
		FisDir:   info.IsDir(),
		Fsys:     info.Sys().(*syscall.Stat_t),
	}

	// Create a response message.
	e.ResMsg = &domain.NSenterMessage{
		Type:    domain.LookupResponse,
		Payload: fileInfo,
	}

	return nil
}

func (e *NSenterEvent) processOpenFileRequest() error {

	payload := e.ReqMsg.Payload.(domain.OpenFilePayload)

	// Extract openflags from the incoming payload.
	openFlags, err := strconv.Atoi(payload.Flags)
	if err != nil {
		return nil
	}

	// Open the file in question. Notice that we are hardcoding the 'mode'
	// argument (third one) as this one is not relevant in a procfs; that
	// is, user cannot create files -- openflags 'O_CREAT' and 'O_TMPFILE'
	// are not expected (refer to "man open(2)" for details).
	_, err = os.OpenFile(payload.File, openFlags, 0)
	if err != nil {
		// Send an error-message response.
		e.ResMsg = &domain.NSenterMessage{
			Type:    domain.ErrorResponse,
			Payload: &fuse.IOerror{RcvError: err},
		}

		return nil
	}

	// Create a response message.
	e.ResMsg = &domain.NSenterMessage{
		Type:    domain.OpenFileResponse,
		Payload: nil,
	}

	return nil
}
func (e *NSenterEvent) processFileReadRequest() error {

	payload := e.ReqMsg.Payload.(domain.ReadFilePayload)

	// Perform read operation and return error msg should this one fail.
	fileContent, err := ioutil.ReadFile(payload.File)
	if err != nil {
		// Send an error-message response.
		e.ResMsg = &domain.NSenterMessage{
			Type:    domain.ErrorResponse,
			Payload: &fuse.IOerror{RcvError: err},
		}

		return err
	}

	// Create a response message.
	e.ResMsg = &domain.NSenterMessage{
		Type:    domain.ReadFileResponse,
		Payload: strings.TrimSpace(string(fileContent)),
	}

	return nil
}

func (e *NSenterEvent) processFileWriteRequest() error {

	payload := e.ReqMsg.Payload.(domain.WriteFilePayload)

	// Perform write operation and return error msg should this one fail.
	err := ioutil.WriteFile(payload.File, []byte(payload.Content), 0644)
	if err != nil {
		// Send an error-message response.
		e.ResMsg = &domain.NSenterMessage{
			Type:    domain.ErrorResponse,
			Payload: &fuse.IOerror{RcvError: err},
		}

		return nil
	}

	// Create a response message.
	e.ResMsg = &domain.NSenterMessage{
		Type:    domain.WriteFileResponse,
		Payload: nil,
	}

	return nil
}

func (e *NSenterEvent) processDirReadRequest() error {

	// Perform readDir operation and return error msg should this one fail.
	dirContent, err := ioutil.ReadDir(e.ReqMsg.Payload.(string))
	if err != nil {
		e.ResMsg = &domain.NSenterMessage{
			Type:    domain.ErrorResponse,
			Payload: err.Error(),
		}

		return err
	}

	// Create a FileInfo slice to return to sysbox-fs' main instance.
	var dirContentList []domain.FileInfo

	for _, entry := range dirContent {
		elem := domain.FileInfo{
			Fname:    entry.Name(),
			Fsize:    entry.Size(),
			Fmode:    entry.Mode(),
			FmodTime: entry.ModTime(),
			FisDir:   entry.IsDir(),
			Fsys:     entry.Sys().(*syscall.Stat_t),
		}
		dirContentList = append(dirContentList, elem)
	}

	// Create a response message.
	e.ResMsg = &domain.NSenterMessage{
		Type:    domain.ReadDirResponse,
		Payload: dirContentList,
	}

	return nil
}

func (e *NSenterEvent) processMountSyscallRequest() error {

	var (
		i   int
		err error
	)

	mountInfoArray := e.ReqMsg.Payload.([]domain.MountSyscallPayload)

	// Perform mount instructions.
	for i = 0; i < len(mountInfoArray); i++ {
		err = unix.Mount(
			mountInfoArray[i].Source,
			mountInfoArray[i].Target,
			mountInfoArray[i].FsType,
			uintptr(mountInfoArray[i].Flags),
			mountInfoArray[i].Data,
		)
		if err != nil {
			// Create error response msg.
			e.ResMsg = &domain.NSenterMessage{
				Type:    domain.ErrorResponse,
				Payload: err.(syscall.Errno),
			}

			break
		}
	}

	if err != nil {
		// Revert previously executed mount instructions.
		for j := i - 1; j >= 0; j-- {
			_ = unix.Unmount(mountInfoArray[j].Target, 0)
		}

		return nil
	}

	// Create success response message.
	e.ResMsg = &domain.NSenterMessage{
		Type:    domain.MountSyscallResponse,
		Payload: "",
	}

	return nil
}

func (e *NSenterEvent) processUmountSyscallRequest() error {

	var (
		i   int
		err error
	)

	umountInfoArray := e.ReqMsg.Payload.([]domain.UmountSyscallPayload)

	// Perform umount instructions.
	for i = 0; i < len(umountInfoArray); i++ {
		err = unix.Unmount(
			umountInfoArray[i].Target,
			int(umountInfoArray[i].Flags),
		)
		if err != nil {
			// Create error response msg.
			e.ResMsg = &domain.NSenterMessage{
				Type:    domain.ErrorResponse,
				Payload: err.(syscall.Errno),
			}

			break
		}
	}

	// If an error is found, notice that we will not revert the changes we could
	// have made thus far. In order to do that (remount), we need information
	// that we don't have at this stage (mount-source, mount-flags, etc). Will
	// leave this 'unwind' logic commented out for now.
	if err != nil {
		// Revert previously executed umount instructions.
		// for j := i - 1; j >= 0; j-- {
		// 	_ = unix.Mount(
		// 		mountInfoArray[j].Source,
		// 		mountInfoArray[j].Target,
		// 		mountInfoArray[j].FsType,
		// 		uintptr(mountInfoArray[j].Flags),
		// 		mountInfoArray[j].Data,
		// 	)
		// }

		return nil
	}

	// Create success response message.
	e.ResMsg = &domain.NSenterMessage{
		Type:    domain.UmountSyscallResponse,
		Payload: "",
	}

	return nil
}

// Method in charge of processing all requests generated by sysbox-fs' master
// instance.
func (e *NSenterEvent) processRequest(pipe io.Reader) error {

	// Rawmessage payload to aid in decoding generic messages (see below
	// explanation).
	var payload json.RawMessage
	nsenterMsg := domain.NSenterMessage{
		Payload: &payload,
	}

	// Decode received msg header to help us determine the payload type.
	// Received message will be decoded in two phases. The decode instruction
	// below help us determine the message-type being received. Based on the
	// obtained type, we are able to decode the payload generated by the
	// remote-end. This second step is executed as part of a subsequent
	// unmarshal instruction (see further below).
	if err := json.NewDecoder(pipe).Decode(&nsenterMsg); err != nil {
		logrus.Errorf("Error decoding received nsenterMsg request (%v).", err)
		return errors.New("Error decoding received event request.")
	}

	switch nsenterMsg.Type {

	case domain.LookupRequest:
		var p string
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ReqMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		return e.processLookupRequest()

	case domain.OpenFileRequest:
		var p domain.OpenFilePayload
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ReqMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		return e.processOpenFileRequest()

	case domain.ReadFileRequest:
		var p domain.ReadFilePayload
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ReqMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		return e.processFileReadRequest()

	case domain.WriteFileRequest:
		var p domain.WriteFilePayload
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ReqMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		return e.processFileWriteRequest()

	case domain.ReadDirRequest:
		var p string
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ReqMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}
		return e.processDirReadRequest()

	case domain.MountSyscallRequest:
		var p []domain.MountSyscallPayload
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ReqMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}

		return e.processMountSyscallRequest()

	case domain.UmountSyscallRequest:
		var p []domain.UmountSyscallPayload
		if payload != nil {
			err := json.Unmarshal(payload, &p)
			if err != nil {
				logrus.Error(err)
				return err
			}
		}

		e.ReqMsg = &domain.NSenterMessage{
			Type:    nsenterMsg.Type,
			Payload: p,
		}

		return e.processUmountSyscallRequest()

	default:
		e.ResMsg = &domain.NSenterMessage{
			Type:    domain.ErrorResponse,
			Payload: "Unsupported request",
		}
	}

	return nil
}

//
// Sysbox-fs' post-nsexec initialization function. To be executed within the
// context of one (or more) container namespaces.
//
func Init() (err error) {

	var (
		pipefd      int
		envInitPipe = os.Getenv("_LIBCONTAINER_INITPIPE")
	)

	// Get the INITPIPE.
	pipefd, err = strconv.Atoi(envInitPipe)
	if err != nil {
		return fmt.Errorf("Unable to convert _LIBCONTAINER_INITPIPE=%s to int: %s",
			envInitPipe, err)
	}

	var pipe = os.NewFile(uintptr(pipefd), "pipe")
	defer pipe.Close()

	// Clear the current process's environment to clean any libcontainer
	// specific env vars.
	os.Clearenv()

	var event NSenterEvent
	err = event.processRequest(pipe)
	if err != nil {
		return err
	}

	// Encode / push response back to sysbox-main.
	data, err := json.Marshal(*(event.ResMsg))
	if err != nil {
		return err
	}
	_, err = pipe.Write(data)

	return nil
}
