// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sysvisor_protobuf.proto

package sysvisor_protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message sent by runC to sysvisorfs process.
type ContainerData struct {
	Id                   string               `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	InitPid              int32                `protobuf:"varint,2,opt,name=InitPid,proto3" json:"InitPid,omitempty"`
	Hostname             string               `protobuf:"bytes,3,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Ctime                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	UidFirst             int32                `protobuf:"varint,5,opt,name=UidFirst,proto3" json:"UidFirst,omitempty"`
	UidSize              int32                `protobuf:"varint,6,opt,name=UidSize,proto3" json:"UidSize,omitempty"`
	GidFirst             int32                `protobuf:"varint,7,opt,name=GidFirst,proto3" json:"GidFirst,omitempty"`
	GidSize              int32                `protobuf:"varint,8,opt,name=GidSize,proto3" json:"GidSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ContainerData) Reset()         { *m = ContainerData{} }
func (m *ContainerData) String() string { return proto.CompactTextString(m) }
func (*ContainerData) ProtoMessage()    {}
func (*ContainerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_77459b2e21c835e2, []int{0}
}

func (m *ContainerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerData.Unmarshal(m, b)
}
func (m *ContainerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerData.Marshal(b, m, deterministic)
}
func (m *ContainerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerData.Merge(m, src)
}
func (m *ContainerData) XXX_Size() int {
	return xxx_messageInfo_ContainerData.Size(m)
}
func (m *ContainerData) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerData.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerData proto.InternalMessageInfo

func (m *ContainerData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContainerData) GetInitPid() int32 {
	if m != nil {
		return m.InitPid
	}
	return 0
}

func (m *ContainerData) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ContainerData) GetCtime() *timestamp.Timestamp {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *ContainerData) GetUidFirst() int32 {
	if m != nil {
		return m.UidFirst
	}
	return 0
}

func (m *ContainerData) GetUidSize() int32 {
	if m != nil {
		return m.UidSize
	}
	return 0
}

func (m *ContainerData) GetGidFirst() int32 {
	if m != nil {
		return m.GidFirst
	}
	return 0
}

func (m *ContainerData) GetGidSize() int32 {
	if m != nil {
		return m.GidSize
	}
	return 0
}

// The response message send from sysvisorfs to runC process.
type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_77459b2e21c835e2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*ContainerData)(nil), "sysvisor_protobuf.ContainerData")
	proto.RegisterType((*Response)(nil), "sysvisor_protobuf.Response")
}

func init() { proto.RegisterFile("sysvisor_protobuf.proto", fileDescriptor_77459b2e21c835e2) }

var fileDescriptor_77459b2e21c835e2 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xff, 0xdb, 0xbf, 0x6d, 0xe3, 0x8a, 0x82, 0x0b, 0xd2, 0x25, 0x1e, 0x0c, 0xc1, 0x43,
	0x4f, 0xa9, 0xd4, 0x93, 0xd7, 0x56, 0xac, 0xbd, 0x95, 0xd4, 0x82, 0x78, 0x91, 0x6d, 0xb3, 0xc6,
	0x81, 0x76, 0x37, 0xec, 0x4e, 0x05, 0x7d, 0x47, 0x9f, 0xc6, 0x17, 0x90, 0x24, 0xdd, 0xa5, 0x12,
	0x8f, 0xde, 0xe6, 0xcb, 0x7c, 0xbf, 0x99, 0x2f, 0x93, 0xd0, 0x9e, 0x7d, 0xb7, 0x6f, 0x60, 0xb5,
	0x79, 0x2e, 0x8c, 0x46, 0xbd, 0xdc, 0xbe, 0x24, 0x55, 0xc1, 0x4e, 0x1b, 0x8d, 0xf0, 0x22, 0xd7,
	0x3a, 0x5f, 0xcb, 0x81, 0x7b, 0x30, 0x40, 0xd8, 0x48, 0x8b, 0x62, 0x53, 0xd4, 0x4c, 0xfc, 0x45,
	0xe8, 0xf1, 0x58, 0x2b, 0x14, 0xa0, 0xa4, 0xb9, 0x15, 0x28, 0xd8, 0x09, 0x6d, 0x4d, 0x33, 0x4e,
	0x22, 0xd2, 0x3f, 0x4c, 0x5b, 0xd3, 0x8c, 0x71, 0xda, 0x9d, 0x2a, 0xc0, 0x19, 0x64, 0xbc, 0x15,
	0x91, 0x7e, 0x3b, 0x75, 0x92, 0x85, 0x34, 0xb8, 0xd7, 0x16, 0x95, 0xd8, 0x48, 0xfe, 0xbf, 0xf2,
	0x7b, 0xcd, 0xae, 0x68, 0x7b, 0x5c, 0xee, 0xe2, 0x07, 0x11, 0xe9, 0x1f, 0x0d, 0xc3, 0xa4, 0x0e,
	0x92, 0xf8, 0xc8, 0x0f, 0x2e, 0x48, 0x5a, 0x1b, 0xcb, 0x69, 0x0b, 0xc8, 0xee, 0xc0, 0x58, 0xe4,
	0xed, 0x6a, 0x91, 0xd7, 0x65, 0x86, 0x05, 0x64, 0x73, 0xf8, 0x90, 0xbc, 0x53, 0x67, 0xd8, 0xc9,
	0x92, 0x9a, 0x38, 0xaa, 0x5b, 0x53, 0x93, 0x3d, 0x6a, 0xb2, 0xa3, 0x82, 0x9a, 0xda, 0xc9, 0xf8,
	0x92, 0x06, 0xa9, 0xb4, 0x85, 0x56, 0x56, 0x96, 0xae, 0xf9, 0x76, 0xb5, 0x92, 0xd6, 0x56, 0x2f,
	0x1d, 0xa4, 0x4e, 0x0e, 0x3f, 0x09, 0x3d, 0xf3, 0xb7, 0x99, 0xa3, 0x40, 0x39, 0x7e, 0x15, 0x4a,
	0xc9, 0x35, 0x7b, 0xdc, 0x6b, 0xa4, 0x32, 0x07, 0x8b, 0x46, 0x20, 0x68, 0xc5, 0xa2, 0xa4, 0xf9,
	0x71, 0x7e, 0x9c, 0x37, 0x3c, 0xff, 0xc5, 0xe1, 0xb2, 0xc4, 0xff, 0xd8, 0x13, 0xed, 0x79, 0xff,
	0x42, 0x99, 0xbf, 0x9c, 0x3d, 0xba, 0xa1, 0x31, 0xe8, 0x24, 0x37, 0xc5, 0xca, 0xfb, 0x9a, 0xc0,
	0xa8, 0xf9, 0x17, 0xcd, 0xc8, 0xb2, 0x53, 0xd5, 0xd7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x09,
	0x71, 0x8a, 0xce, 0x7c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContainerStateChannelClient is the client API for ContainerStateChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContainerStateChannelClient interface {
	// Generates a container-registration message
	ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
}

type containerStateChannelClient struct {
	cc *grpc.ClientConn
}

func NewContainerStateChannelClient(cc *grpc.ClientConn) ContainerStateChannelClient {
	return &containerStateChannelClient{cc}
}

func (c *containerStateChannelClient) ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/sysvisor_protobuf.ContainerStateChannel/ContainerRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerStateChannelClient) ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/sysvisor_protobuf.ContainerStateChannel/ContainerUnregistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerStateChannelServer is the server API for ContainerStateChannel service.
type ContainerStateChannelServer interface {
	// Generates a container-registration message
	ContainerRegistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(context.Context, *ContainerData) (*Response, error)
}

func RegisterContainerStateChannelServer(s *grpc.Server, srv ContainerStateChannelServer) {
	s.RegisterService(&_ContainerStateChannel_serviceDesc, srv)
}

func _ContainerStateChannel_ContainerRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerStateChannelServer).ContainerRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysvisor_protobuf.ContainerStateChannel/ContainerRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerStateChannelServer).ContainerRegistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerStateChannel_ContainerUnregistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerStateChannelServer).ContainerUnregistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sysvisor_protobuf.ContainerStateChannel/ContainerUnregistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerStateChannelServer).ContainerUnregistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContainerStateChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sysvisor_protobuf.ContainerStateChannel",
	HandlerType: (*ContainerStateChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContainerRegistration",
			Handler:    _ContainerStateChannel_ContainerRegistration_Handler,
		},
		{
			MethodName: "ContainerUnregistration",
			Handler:    _ContainerStateChannel_ContainerUnregistration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysvisor_protobuf.proto",
}
