//
// Copyright 2019-2020 Nestybox, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/nestybox/sysbox-fs/domain"
	mock "github.com/stretchr/testify/mock"
)

// FuseServerServiceIface is an autogenerated mock type for the FuseServerServiceIface type
type FuseServerServiceIface struct {
	mock.Mock
}

// CreateFuseServer provides a mock function with given fields: cntr
func (_m *FuseServerServiceIface) CreateFuseServer(cntr domain.ContainerIface) error {
	ret := _m.Called(cntr)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ContainerIface) error); ok {
		r0 = rf(cntr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DestroyFuseServer provides a mock function with given fields: mp
func (_m *FuseServerServiceIface) DestroyFuseServer(mp string) error {
	ret := _m.Called(mp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DestroyFuseService provides a mock function with given fields:
func (_m *FuseServerServiceIface) DestroyFuseService() {
	_m.Called()
}

// Setup provides a mock function with given fields: mp, css, ios, hds
func (_m *FuseServerServiceIface) Setup(mp string, css domain.ContainerStateServiceIface, ios domain.IOServiceIface, hds domain.HandlerServiceIface) {
	_m.Called(mp, css, ios, hds)
}
