//
// Copyright 2019-2020 Nestybox, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/nestybox/sysbox-fs/domain"
	mock "github.com/stretchr/testify/mock"

	os "os"
)

// IOServiceIface is an autogenerated mock type for the IOServiceIface type
type IOServiceIface struct {
	mock.Mock
}

// GetServiceType provides a mock function with given fields:
func (_m *IOServiceIface) GetServiceType() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewIOnode provides a mock function with given fields: n, p, attr
func (_m *IOServiceIface) NewIOnode(n string, p string, attr os.FileMode) domain.IOnodeIface {
	ret := _m.Called(n, p, attr)

	var r0 domain.IOnodeIface
	if rf, ok := ret.Get(0).(func(string, string, os.FileMode) domain.IOnodeIface); ok {
		r0 = rf(n, p, attr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.IOnodeIface)
		}
	}

	return r0
}

// RemoveAllIOnodes provides a mock function with given fields:
func (_m *IOServiceIface) RemoveAllIOnodes() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
