// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "github.com/nestybox/sysbox-fs/domain"
import mock "github.com/stretchr/testify/mock"

// NSenterEventIface is an autogenerated mock type for the NSenterEventIface type
type NSenterEventIface struct {
	mock.Mock
}

// Launch provides a mock function with given fields:
func (_m *NSenterEventIface) Launch() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Response provides a mock function with given fields:
func (_m *NSenterEventIface) Response() *domain.NSenterMessage {
	ret := _m.Called()

	var r0 *domain.NSenterMessage
	if rf, ok := ret.Get(0).(func() *domain.NSenterMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.NSenterMessage)
		}
	}

	return r0
}
