//
// Sysbox-fs Protobuffer Definitions.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: sysboxFsProtobuf.proto

package sysboxFsProtobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message sent by runC to sysbox-fs process during container
// registration, unregistration and update phases.
type ContainerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	InitPid       int32                  `protobuf:"varint,2,opt,name=InitPid,proto3" json:"InitPid,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Ctime         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Ctime,proto3" json:"Ctime,omitempty"`
	UidFirst      int32                  `protobuf:"varint,5,opt,name=UidFirst,proto3" json:"UidFirst,omitempty"`
	UidSize       int32                  `protobuf:"varint,6,opt,name=UidSize,proto3" json:"UidSize,omitempty"`
	GidFirst      int32                  `protobuf:"varint,7,opt,name=GidFirst,proto3" json:"GidFirst,omitempty"`
	GidSize       int32                  `protobuf:"varint,8,opt,name=GidSize,proto3" json:"GidSize,omitempty"`
	ProcRoPaths   []string               `protobuf:"bytes,9,rep,name=ProcRoPaths,proto3" json:"ProcRoPaths,omitempty"`
	ProcMaskPaths []string               `protobuf:"bytes,10,rep,name=ProcMaskPaths,proto3" json:"ProcMaskPaths,omitempty"`
	Netns         string                 `protobuf:"bytes,11,opt,name=Netns,proto3" json:"Netns,omitempty"`
}

func (x *ContainerData) Reset() {
	*x = ContainerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysboxFsProtobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerData) ProtoMessage() {}

func (x *ContainerData) ProtoReflect() protoreflect.Message {
	mi := &file_sysboxFsProtobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerData.ProtoReflect.Descriptor instead.
func (*ContainerData) Descriptor() ([]byte, []int) {
	return file_sysboxFsProtobuf_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerData) GetInitPid() int32 {
	if x != nil {
		return x.InitPid
	}
	return 0
}

func (x *ContainerData) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ContainerData) GetCtime() *timestamppb.Timestamp {
	if x != nil {
		return x.Ctime
	}
	return nil
}

func (x *ContainerData) GetUidFirst() int32 {
	if x != nil {
		return x.UidFirst
	}
	return 0
}

func (x *ContainerData) GetUidSize() int32 {
	if x != nil {
		return x.UidSize
	}
	return 0
}

func (x *ContainerData) GetGidFirst() int32 {
	if x != nil {
		return x.GidFirst
	}
	return 0
}

func (x *ContainerData) GetGidSize() int32 {
	if x != nil {
		return x.GidSize
	}
	return 0
}

func (x *ContainerData) GetProcRoPaths() []string {
	if x != nil {
		return x.ProcRoPaths
	}
	return nil
}

func (x *ContainerData) GetProcMaskPaths() []string {
	if x != nil {
		return x.ProcMaskPaths
	}
	return nil
}

func (x *ContainerData) GetNetns() string {
	if x != nil {
		return x.Netns
	}
	return ""
}

// Response message sent from sysbox-fs to runC process.
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysboxFsProtobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sysboxFsProtobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sysboxFsProtobuf_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MountpointReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MountpointReq) Reset() {
	*x = MountpointReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysboxFsProtobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountpointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountpointReq) ProtoMessage() {}

func (x *MountpointReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysboxFsProtobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountpointReq.ProtoReflect.Descriptor instead.
func (*MountpointReq) Descriptor() ([]byte, []int) {
	return file_sysboxFsProtobuf_proto_rawDescGZIP(), []int{2}
}

type MountpointResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mountpoint string `protobuf:"bytes,1,opt,name=Mountpoint,proto3" json:"Mountpoint,omitempty"`
}

func (x *MountpointResp) Reset() {
	*x = MountpointResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sysboxFsProtobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MountpointResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountpointResp) ProtoMessage() {}

func (x *MountpointResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysboxFsProtobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountpointResp.ProtoReflect.Descriptor instead.
func (*MountpointResp) Descriptor() ([]byte, []int) {
	return file_sysboxFsProtobuf_proto_rawDescGZIP(), []int{3}
}

func (x *MountpointResp) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

var File_sysboxFsProtobuf_proto protoreflect.FileDescriptor

var file_sysboxFsProtobuf_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x79, 0x73, 0x62, 0x6f, 0x78, 0x46, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd1, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x50, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x43,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x43, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x69, 0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x55, 0x69, 0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x55, 0x69, 0x64,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x55, 0x69, 0x64, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x69, 0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x47, 0x69, 0x64, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x47, 0x69, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x47, 0x69, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x63, 0x52, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x50, 0x72, 0x6f, 0x63, 0x52, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x50,
	0x72, 0x6f, 0x63, 0x4d, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x74, 0x68, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x4d, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x74, 0x68,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x65, 0x74, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x4e, 0x65, 0x74, 0x6e, 0x73, 0x22, 0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x0f, 0x0a,
	0x0d, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x22, 0x30,
	0x0a, 0x0e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x32, 0xf9, 0x02, 0x0a, 0x12, 0x73, 0x79, 0x73, 0x62, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x44, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x6f,
	0x75, 0x6e, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x6f, 0x75,
	0x6e, 0x74, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x18, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x50, 0x72, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x48, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x55, 0x6e, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13,
	0x2e, 0x2f, 0x3b, 0x73, 0x79, 0x73, 0x62, 0x6f, 0x78, 0x46, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sysboxFsProtobuf_proto_rawDescOnce sync.Once
	file_sysboxFsProtobuf_proto_rawDescData = file_sysboxFsProtobuf_proto_rawDesc
)

func file_sysboxFsProtobuf_proto_rawDescGZIP() []byte {
	file_sysboxFsProtobuf_proto_rawDescOnce.Do(func() {
		file_sysboxFsProtobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_sysboxFsProtobuf_proto_rawDescData)
	})
	return file_sysboxFsProtobuf_proto_rawDescData
}

var file_sysboxFsProtobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sysboxFsProtobuf_proto_goTypes = []interface{}{
	(*ContainerData)(nil),         // 0: protobuf.ContainerData
	(*Response)(nil),              // 1: protobuf.Response
	(*MountpointReq)(nil),         // 2: protobuf.MountpointReq
	(*MountpointResp)(nil),        // 3: protobuf.MountpointResp
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_sysboxFsProtobuf_proto_depIdxs = []int32{
	4, // 0: protobuf.ContainerData.Ctime:type_name -> google.protobuf.Timestamp
	2, // 1: protobuf.sysboxStateChannel.GetMountpoint:input_type -> protobuf.MountpointReq
	0, // 2: protobuf.sysboxStateChannel.ContainerPreRegistration:input_type -> protobuf.ContainerData
	0, // 3: protobuf.sysboxStateChannel.ContainerRegistration:input_type -> protobuf.ContainerData
	0, // 4: protobuf.sysboxStateChannel.ContainerUnregistration:input_type -> protobuf.ContainerData
	0, // 5: protobuf.sysboxStateChannel.ContainerUpdate:input_type -> protobuf.ContainerData
	3, // 6: protobuf.sysboxStateChannel.GetMountpoint:output_type -> protobuf.MountpointResp
	1, // 7: protobuf.sysboxStateChannel.ContainerPreRegistration:output_type -> protobuf.Response
	1, // 8: protobuf.sysboxStateChannel.ContainerRegistration:output_type -> protobuf.Response
	1, // 9: protobuf.sysboxStateChannel.ContainerUnregistration:output_type -> protobuf.Response
	1, // 10: protobuf.sysboxStateChannel.ContainerUpdate:output_type -> protobuf.Response
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sysboxFsProtobuf_proto_init() }
func file_sysboxFsProtobuf_proto_init() {
	if File_sysboxFsProtobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sysboxFsProtobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysboxFsProtobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysboxFsProtobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountpointReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sysboxFsProtobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MountpointResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sysboxFsProtobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysboxFsProtobuf_proto_goTypes,
		DependencyIndexes: file_sysboxFsProtobuf_proto_depIdxs,
		MessageInfos:      file_sysboxFsProtobuf_proto_msgTypes,
	}.Build()
	File_sysboxFsProtobuf_proto = out.File
	file_sysboxFsProtobuf_proto_rawDesc = nil
	file_sysboxFsProtobuf_proto_goTypes = nil
	file_sysboxFsProtobuf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SysboxStateChannelClient is the client API for SysboxStateChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SysboxStateChannelClient interface {
	// Queries sysbox-fs for the FUSE mountpoint
	GetMountpoint(ctx context.Context, in *MountpointReq, opts ...grpc.CallOption) (*MountpointResp, error)
	// Generates a container-preregistration message
	ContainerPreRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-registration message
	ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
	// Generates a container-update message
	ContainerUpdate(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error)
}

type sysboxStateChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewSysboxStateChannelClient(cc grpc.ClientConnInterface) SysboxStateChannelClient {
	return &sysboxStateChannelClient{cc}
}

func (c *sysboxStateChannelClient) GetMountpoint(ctx context.Context, in *MountpointReq, opts ...grpc.CallOption) (*MountpointResp, error) {
	out := new(MountpointResp)
	err := c.cc.Invoke(ctx, "/protobuf.sysboxStateChannel/GetMountpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerPreRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.sysboxStateChannel/ContainerPreRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerRegistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.sysboxStateChannel/ContainerRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerUnregistration(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.sysboxStateChannel/ContainerUnregistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysboxStateChannelClient) ContainerUpdate(ctx context.Context, in *ContainerData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.sysboxStateChannel/ContainerUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysboxStateChannelServer is the server API for SysboxStateChannel service.
type SysboxStateChannelServer interface {
	// Queries sysbox-fs for the FUSE mountpoint
	GetMountpoint(context.Context, *MountpointReq) (*MountpointResp, error)
	// Generates a container-preregistration message
	ContainerPreRegistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-registration message
	ContainerRegistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-unregistration message
	ContainerUnregistration(context.Context, *ContainerData) (*Response, error)
	// Generates a container-update message
	ContainerUpdate(context.Context, *ContainerData) (*Response, error)
}

// UnimplementedSysboxStateChannelServer can be embedded to have forward compatible implementations.
type UnimplementedSysboxStateChannelServer struct {
}

func (*UnimplementedSysboxStateChannelServer) GetMountpoint(context.Context, *MountpointReq) (*MountpointResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMountpoint not implemented")
}
func (*UnimplementedSysboxStateChannelServer) ContainerPreRegistration(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerPreRegistration not implemented")
}
func (*UnimplementedSysboxStateChannelServer) ContainerRegistration(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerRegistration not implemented")
}
func (*UnimplementedSysboxStateChannelServer) ContainerUnregistration(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUnregistration not implemented")
}
func (*UnimplementedSysboxStateChannelServer) ContainerUpdate(context.Context, *ContainerData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerUpdate not implemented")
}

func RegisterSysboxStateChannelServer(s *grpc.Server, srv SysboxStateChannelServer) {
	s.RegisterService(&_SysboxStateChannel_serviceDesc, srv)
}

func _SysboxStateChannel_GetMountpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountpointReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).GetMountpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysboxStateChannel/GetMountpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).GetMountpoint(ctx, req.(*MountpointReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerPreRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerPreRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysboxStateChannel/ContainerPreRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerPreRegistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysboxStateChannel/ContainerRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerRegistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerUnregistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerUnregistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysboxStateChannel/ContainerUnregistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerUnregistration(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysboxStateChannel_ContainerUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxStateChannelServer).ContainerUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.sysboxStateChannel/ContainerUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxStateChannelServer).ContainerUpdate(ctx, req.(*ContainerData))
	}
	return interceptor(ctx, in, info, handler)
}

var _SysboxStateChannel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.sysboxStateChannel",
	HandlerType: (*SysboxStateChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMountpoint",
			Handler:    _SysboxStateChannel_GetMountpoint_Handler,
		},
		{
			MethodName: "ContainerPreRegistration",
			Handler:    _SysboxStateChannel_ContainerPreRegistration_Handler,
		},
		{
			MethodName: "ContainerRegistration",
			Handler:    _SysboxStateChannel_ContainerRegistration_Handler,
		},
		{
			MethodName: "ContainerUnregistration",
			Handler:    _SysboxStateChannel_ContainerUnregistration_Handler,
		},
		{
			MethodName: "ContainerUpdate",
			Handler:    _SysboxStateChannel_ContainerUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysboxFsProtobuf.proto",
}
